### ISSUE TITLE
How to avoid embedding access_token?

### ISSUE THREAD

**Issue by robmarkcole** [roboflow-ai/bccd_streamlit_app_public#2]
Hi, nice app!
On the onehand it is nice to use streamlit sharing with public repo, to have free hosting of the app. However the roadblock against use is the need to having public repo and no obvious way to do things like storing credentials in the app securely. I notice you have the `access_token` embedded in the app. Did you think of any alternative routes?

**Comment by yeldarby** [comment]
We couldn’t think of anything offhand so we scoped that token for use with only this dataset.

Presumably you could have a textfield in the UI where the user has to enter the key themselves (which is what we do on https://infer.roboflow.com with a prefill-via-URL option).

Let us check with Streamlit and see if they have any other ideas.

**Comment by matthewbrems** [comment]
Thanks, @robmarkcole! Much appreciated.

Streamlit shared that hiding secret keys in public repos is currently in beta but should soon be on the [free tier](https://www.streamlit.io/sharing). They also support private Github repos on their [Enterprise tier](https://www.streamlit.io/for-teams). 

At present, our best solution is to do what @yeldarby suggests above in the UI or to pick a "throwaway" key that's just for that purpose.

**Comment by robmarkcole** [comment]
Thanks for the info @matthewbrems I will look out for their announcements. In the meantime [in my fork](https://github.com/robmarkcole/roboflow-inference-streamlit) I am just using a text input to add the key. Cheers
